[book]
title = "puddingOS"
authors = ["Jack Jones"]
language = "en"
src = "src"

[output.html]
site-url = "https://jackmj1024.github.io/puddingOS"
git-repository-url = "https://github.com/jackmj1024/puddingOS"
edit-url-template = "{path}"
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
additional-css = ["./theme/catppuccin.css", "./theme/extra.css"]
no-section-label = true
