name: Deploy Documentation
on:
    push:
        branches:
            - release-25.11
permissions:
    contents: read
    pages: write
    id-token: write
concurrency:
    group: pages
    cancel-in-progress: true
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout.
              uses: actions/checkout@v4

            - name: Install Nix.
              uses: cachix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-25.11

            - name: Build documentation.
              run: nix-build docs

            - name: Prepare artifact.
              run: |
                  cp -rL result public-docs
                  chmod -R u+w public-docs

            - name: Upload pages artifact.
              uses: actions/upload-pages-artifact@v3
              with:
                  path: public-docs

            - name: Deploy to GitHub Pages.
              id: deployment
              uses: actions/deploy-pages@v4
